### ISSUE TITLE
coconut + name in a batch should give them to the specified person

### ISSUE THREAD

**Issue by choutrang** [alecc08/heycoconut#23]
:coconut: person1 :coconut: person2 :coconut:person3

result : person1 received 3 coconuts

what we should have instead: each person receive a coconut

**Comment by alecc08** [comment]
labelled as enhancement instead of bug, since this was the way it was supposed to work, but i agree it'd be a nice feature to tag individually

**Comment by RaymondAudet** [comment]
@choutrang @alecc08 What happens if the user don't have enough coconuts to give to all the people in his message? Should we reply an error and don't add any, Spread the cocos evenly the best we can or simply give all the cocos to the 1st person in the message?

**Comment by alecc08** [comment]
currently it's "First come first serve" where the coconuts get distributed in order. As soon as they run out, an error message is given but the previous people correctly receive their coconuts

**Comment by alecc08** [comment]
I think we should close this issue, the current way seems to be working out well and follows the KISS principle 😛
